export const initialData = [
  {
    id: '1_n',
    title: 'note1',
    isFolder: false,
    parent_id: null,
    sorting: 0,
  },
  {
    id: '2_n',
    title: 'note2',
    isFolder: false,
    parent_id: null,
    sorting: 1,
  },
  {
    id: '3_n',
    title: 'note3',
    isFolder: false,
    parent_id: '1_fol',
    sorting: 2,
  },
  {
    id: '4_n',
    title: 'note4',
    isFolder: false,
    parent_id: null,
    sorting: 3,
  },
  {
    id: '5_n',
    title: 'note5',
    isFolder: false,
    parent_id: null,
    sorting: 4,
  },
  {
    id: '1_fol',
    title: 'folder1',
    isFolder: true,
    parent_id: null,
    sorting: 5,
  },
];

export const style = {
  searchContainer: {
    position: 'relative',
    marginBottom: '10px',
    maxWidth: '320px',
  },
  nodeStyle: {
    cursor: 'pointer',
    borderRadius: '5px',
    userSelect: 'none',
    selectedColor: '#FFB703',
    hoveredColor: '#FFF5DD',
    backgroundColor: 'transparent',
  },
  searchInput: {
    border: '0',
    borderBottom: '1px solid #555',
    background: 'transparent',
    width: '100%',
    padding: '24px 0 5px 0',
    fontSize: '14px',
    outline: 'none',
  },
  searchLabel: {
    position: 'absolute',
    top: '0px',
    left: '0px',
    fontSize: '14px',
    color: '#555',
    transition: 'all 0.5s ease-in-out',
  },
  contextMenuContainer: {
    position: 'absolute',
    backgroundColor: 'white',
    border: '1px solid #ccc',
    borderRadius: '5px',
    boxShadow: '2px 2px 5px rgba(0, 0, 0, 0.3)',
    zIndex: '100',
    whiteSpace: 'nowrap',
  },
  contextMenuItem: {
    padding: '4px 30px 4px 10px',
    cursor: 'pointer',
    hoveredColor: '#EDEDED',
    backgroundColor: 'transparent',
  },
  contextMenuWrapperStyle: { position: 'fixed', zIndex: 50 },
};
